# Generated by Django 6.0.4 on 2026-05-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_hospital_status_alter_hospital_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parent_photos/'),
        ),
    ]
