# Generated by Django 6.0.4 on 2026-05-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
